'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _47013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("47013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4802552_orig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4802552_orig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _541077_bigthumbnail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("541077-bigthumbnail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property abstract_dark_grid_hex_3d_1280x800_wallpaper_www_wallpaperfo_com_93() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract dark grid hex 3d 1280x800 wallpaper_www.wallpaperfo.com_93", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Alienware_Logo_Desktop_Wallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alienware-Logo-Desktop-Wallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beautiful_girl_light_graffiti_163889() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beautiful-girl-light-graffiti_163889", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property black_wood_3d_this_2560x1600_wallpaper_wallpaperswa_com_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black wood 3d this 2560x1600 wallpaper_wallpaperswa.com_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dark_3D_Wallpapers_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark 3D Wallpapers 01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property drones_nypd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drones-nypd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DroneWallpaper1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DroneWallpaper1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hubsan_x4_camera_edition_mini_quadcopter_2_4ghz_rtf_mode_2__4422_p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hubsan-x4-camera-edition-mini-quadcopter-2.4ghz-rtf-mode-2--4422-p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monochrome_wooden_box_wallpapers_35716_1280x800() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monochrome-wooden-box-wallpapers_35716_1280x800", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oblivion_drones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oblivion-drones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oblivion_drones1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oblivion-drones1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property testo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("testo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property testo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("testo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property the_eye_wallpaper_by_box1515_d41ta37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_eye_wallpaper_by_box1515-d41ta37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XEU_Drone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XEU_Drone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xlarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xlarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
